# Arquivo: configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app-namespace
data:
  # Configurações do Banco de Dados (para o Backend Flask)
  DB_HOST: "postgres-service.db-namespace.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "messages_db"

  # Configurações da API (Backend Flask)
  API_HOST: "0.0.0.0"
  API_PORT: "5000"

  # Configurações do Frontend (React/VITE)
  VITE_API_URL: "/api/"
